export enki_location=${(%):-%N}

enki_location=`readlink $enki_location`
enki_location=`dirname $enki_location`
enki_location=$enki_location/..

export omz_custom_location=${enki_location}/.omz-custom
export ohmyzsh_location=${enki_location}/.oh-my-zsh

# Ensure that anything we need here but dont want shared with
# the world is loaded.

[ -e "$HOME/.zsh_private" ] && source "$HOME/.zsh_private"

# [ -e "${enki_location}/.zsh_aliases" ] && source "${enki_location}/.zsh_aliases"
# [ -e "${enki_location}/.zshrc_local" ] && source "${enki_location}/.zshrc_local"

# You have to use npm to install npm, and that will give you the
# completionaphe.sh file you need.
#source /opt/local/lib/node_modules/npm/lib/utils/completion.sh

export ZSH_CUSTOM=${omz_custom_location}
export ZSH=${ohmyzsh_location}

zstyle ':completion:*' verbose yes
zstyle ':completion:*:descriptions' format '%B%d%b'
zstyle ':completion:*:messages' format '%d'
zstyle ':completion:*:warnings' format 'No matches for: %d'
zstyle ':completion:*' group-name''

[[ -z $ZSH_THEME ]] && ZSH_THEME="agnoster" #"apheleia"
plugins=(git osx git-flow github)
# plugins=($plugins $project_plugins)

[ -e "$ZSH/oh-my-zsh.sh" ] && source "$ZSH/oh-my-zsh.sh"

autoload -U promptinit
promptinit

source ${enki_location}/scripts/source/source_my_scripts

# mmv *.foo *.bar
# This zmv enables mass renaming feature.
# This is a zsh feature
autoload -U zmv
alias mmv='noglob zmv -W'

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
export PATH=$PATH:/usr/local/share/dotnet



